apiVersion: v1
kind: Service
metadata:
  name: weather-app-service # Name for the service object
spec:
  type: NodePort # Use NodePort for easy access in Minikube
  selector:
    app: weather-app # Selects pods with the label 'app: weather-app'
  ports:
  - protocol: TCP
    port: 80 # Port the service will be available on INSIDE the cluster
    targetPort: 3000 # Port on the PODs to forward traffic to (must match containerPort in deployment)
    # nodePort: 30080 # Optional: Specify a static NodePort (if omitted, Kubernetes assigns one)
