apiVersion: v1
kind: Service
metadata:
  name: weather-app-service # Name for the service object
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 80 # Port the service listens on *within* the cluster
    targetPort: 80 # <<< MUST MATCH containerPort in Deployment
    # nodePort: 30080 # Optional static nodePort
